# Generated by Django 3.2.9 on 2021-11-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20211109_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='videoId',
            new_name='video_id',
        ),
    ]
